// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todolist.proto

/*
Package todolist is a generated protocol buffer package.

It is generated from these files:
	todolist.proto

It has these top-level messages:
	Todo
*/
package todolist

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Todo_State int32

const (
	Todo_NOT_COMPLETED Todo_State = 0
	Todo_COMPLETED     Todo_State = 1
)

var Todo_State_name = map[int32]string{
	0: "NOT_COMPLETED",
	1: "COMPLETED",
}
var Todo_State_value = map[string]int32{
	"NOT_COMPLETED": 0,
	"COMPLETED":     1,
}

func (x Todo_State) String() string {
	return proto.EnumName(Todo_State_name, int32(x))
}
func (Todo_State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

type Todo struct {
	Id      int32      `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Title   string     `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	DueDate string     `protobuf:"bytes,3,opt,name=due_date,json=dueDate" json:"due_date,omitempty"`
	Owner   string     `protobuf:"bytes,4,opt,name=owner" json:"owner,omitempty"`
	State   Todo_State `protobuf:"varint,5,opt,name=state,enum=todolist.Todo_State" json:"state,omitempty"`
}

func (m *Todo) Reset()                    { *m = Todo{} }
func (m *Todo) String() string            { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()               {}
func (*Todo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Todo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Todo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Todo) GetDueDate() string {
	if m != nil {
		return m.DueDate
	}
	return ""
}

func (m *Todo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Todo) GetState() Todo_State {
	if m != nil {
		return m.State
	}
	return Todo_NOT_COMPLETED
}

func init() {
	proto.RegisterType((*Todo)(nil), "todolist.Todo")
	proto.RegisterEnum("todolist.Todo_State", Todo_State_name, Todo_State_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TodoList service

type TodoListClient interface {
	ListTodos(ctx context.Context, in *Todo, opts ...grpc.CallOption) (TodoList_ListTodosClient, error)
}

type todoListClient struct {
	cc *grpc.ClientConn
}

func NewTodoListClient(cc *grpc.ClientConn) TodoListClient {
	return &todoListClient{cc}
}

func (c *todoListClient) ListTodos(ctx context.Context, in *Todo, opts ...grpc.CallOption) (TodoList_ListTodosClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TodoList_serviceDesc.Streams[0], c.cc, "/todolist.TodoList/ListTodos", opts...)
	if err != nil {
		return nil, err
	}
	x := &todoListListTodosClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TodoList_ListTodosClient interface {
	Recv() (*Todo, error)
	grpc.ClientStream
}

type todoListListTodosClient struct {
	grpc.ClientStream
}

func (x *todoListListTodosClient) Recv() (*Todo, error) {
	m := new(Todo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TodoList service

type TodoListServer interface {
	ListTodos(*Todo, TodoList_ListTodosServer) error
}

func RegisterTodoListServer(s *grpc.Server, srv TodoListServer) {
	s.RegisterService(&_TodoList_serviceDesc, srv)
}

func _TodoList_ListTodos_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Todo)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TodoListServer).ListTodos(m, &todoListListTodosServer{stream})
}

type TodoList_ListTodosServer interface {
	Send(*Todo) error
	grpc.ServerStream
}

type todoListListTodosServer struct {
	grpc.ServerStream
}

func (x *todoListListTodosServer) Send(m *Todo) error {
	return x.ServerStream.SendMsg(m)
}

var _TodoList_serviceDesc = grpc.ServiceDesc{
	ServiceName: "todolist.TodoList",
	HandlerType: (*TodoListServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListTodos",
			Handler:       _TodoList_ListTodos_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "todolist.proto",
}

func init() { proto.RegisterFile("todolist.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 255 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x41, 0x4a, 0xc3, 0x40,
	0x14, 0x86, 0x9d, 0xd8, 0x68, 0xf2, 0xa0, 0xa1, 0x3e, 0x8a, 0xc4, 0xe2, 0x22, 0x64, 0x15, 0x5d,
	0x24, 0x52, 0x8f, 0x60, 0xb3, 0xab, 0x56, 0x63, 0xf6, 0x65, 0x64, 0x86, 0x32, 0x10, 0xf2, 0x4a,
	0xe7, 0x15, 0xf7, 0x5e, 0xc1, 0xab, 0x78, 0x13, 0xaf, 0xe0, 0x41, 0x64, 0x26, 0xa8, 0xd8, 0xd5,
	0xf0, 0xf1, 0xfd, 0x3f, 0x6f, 0xf8, 0x21, 0x61, 0x52, 0xd4, 0x19, 0xcb, 0xe5, 0x76, 0x47, 0x4c,
	0x18, 0xfd, 0xf0, 0xec, 0x72, 0x43, 0xb4, 0xe9, 0x74, 0x25, 0xb7, 0xa6, 0x92, 0x7d, 0x4f, 0x2c,
	0xd9, 0x50, 0x6f, 0x87, 0x5c, 0xfe, 0x21, 0x60, 0xd4, 0x92, 0x22, 0x4c, 0x20, 0x30, 0x2a, 0x15,
	0x99, 0x28, 0xc2, 0x26, 0x30, 0x0a, 0xa7, 0x10, 0xb2, 0xe1, 0x4e, 0xa7, 0x41, 0x26, 0x8a, 0xb8,
	0x19, 0x00, 0x2f, 0x20, 0x52, 0x7b, 0xbd, 0x56, 0x92, 0x75, 0x7a, 0xec, 0xc5, 0xa9, 0xda, 0xeb,
	0x85, 0x64, 0xed, 0x0a, 0xf4, 0xda, 0xeb, 0x5d, 0x3a, 0x1a, 0x0a, 0x1e, 0xf0, 0x1a, 0x42, 0xcb,
	0x2e, 0x1d, 0x66, 0xa2, 0x48, 0xe6, 0xd3, 0xf2, 0xf7, 0x9f, 0xee, 0x6a, 0xf9, 0xec, 0x5c, 0x33,
	0x44, 0xf2, 0x2b, 0x08, 0x3d, 0xe3, 0x19, 0x8c, 0x1f, 0x56, 0xed, 0xfa, 0x6e, 0x75, 0xff, 0xb8,
	0xac, 0xdb, 0x7a, 0x31, 0x39, 0xc2, 0x31, 0xc4, 0x7f, 0x28, 0xe6, 0x4f, 0x10, 0xb9, 0xfe, 0xd2,
	0x58, 0xc6, 0x1a, 0x62, 0xf7, 0x3a, 0xb6, 0x98, 0xfc, 0x3f, 0x30, 0x3b, 0xe0, 0xfc, 0xfc, 0xed,
	0xf3, 0xeb, 0x3d, 0x98, 0x60, 0xe2, 0xf7, 0x70, 0xae, 0x72, 0xf2, 0x46, 0xbc, 0x9c, 0xf8, 0x41,
	0x6e, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x17, 0x8a, 0x14, 0x31, 0x4a, 0x01, 0x00, 0x00,
}
